theme: jekyll-theme-minimal
## Welcome to Sam Frost's homepage!
My name is Sam Frost and I come from Buffalo, NY. I went to Sweet Home High School and I aspire to some day work at Nintendo. I love playing video games, mostly on my Nintendo Switch, but I do plan on getting the Playstation 5 when that comes out. I'm also really into music, some of my favorite bands include My Chemical Romance, Paramore, Weezer, System of a Down and Green Day. I've been playing guitar for about two and a half years and I don't plan on stopping anytime soon!

! [](https://www.modernhoney.com/wp-content/uploads/2018/08/Fettuccine-Alfredo-Recipe-1.jpg)
My Mom makes he best fettucini alfredo!
