theme: jekyll-theme-minimal
## Welcome to Sam Frost's homepage!
description: My name is Sam Frost and I come from Buffalo, NY. I went to Sweet Home High School and I aspire to some day work at Nintendo. I love playing video games, mostly on my Nintendo Switch, but I do plan on getting the Playstation 5 when that comes out. Im also really into music, some of my favorite bands include My Chemical Romance, Paramore, Weezer, System of a Down and Green Day. Ive been playing guitar for about two and a half years and I dont plan on stopping anytime soon!
## My Favorite Food
![Image](http://github.com/Frosty8651/Frosty8651.github.io/issues/1#issue-709805317)
## My Major
[Link](http://www.rit.edu/computing/department-software-engineering)
## What Id like to learn
- How to create apps
- How to execute code through different means other than terminal/powershell
- Game development
- What SEs actually do for software
- Doing that exact thing
