theme: jekyll-theme-minimal
## Welcome to Sam Frost's homepage!
description: My name is Sam Frost and I come from Buffalo, NY. I went to Sweet Home High School and I aspire to some day work at Nintendo. I love playing video games, mostly on my Nintendo Switch, but I do plan on getting the Playstation 5 when that comes out. Im also really into music, some of my favorite bands include My Chemical Romance, Paramore, Weezer, System of a Down and Green Day. Ive been playing guitar for about two and a half years and I dont plan on stopping anytime soon!
## My Favorite Food
![image](https://camo.githubusercontent.com/328557d56bcef9956f634d7d73d9b0bd0fa64725/68747470733a2f2f7777772e6d6f6465726e686f6e65792e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f30382f46657474756363696e652d416c667265646f2d5265636970652d312e6a7067)
## Software Engineer Major
[Link](https://www.rit.edu/computing/department-software-engineering)
## What I'd Like to Learn
What Id like to learn
- How to create apps
- How to execute code through different means other than terminal/powershell
- Game development
- What SEs actually do for software
- Doing that exact thing
